# Generated by Django 4.1.5 on 2023-03-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="torphies2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
