# Generated by Django 4.1.5 on 2023-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc",
            name="char",
        ),
        migrations.RemoveField(
            model_name="doc",
            name="text",
        ),
        migrations.AddField(
            model_name="doc",
            name="data",
            field=models.JSONField(default={"test": "test1"}),
            preserve_default=False,
        ),
    ]
