# Generated by Django 4.1.5 on 2023-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="data_date",
            field=models.DateTimeField(default="2012-01-01 12:00:00"),
            preserve_default=False,
        ),
    ]
