# Generated by Django 4.1.5 on 2023-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="test",
            field=models.CharField(default="test", max_length=25),
            preserve_default=False,
        ),
    ]
