# Generated by Django 4.1.5 on 2023-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_remove_doc_char_remove_doc_text_doc_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="user_id",
            field=models.IntegerField(default=1),
        ),
    ]
