# Generated by Django 4.1.5 on 2023-02-16 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_doc_data_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doc",
            options={"get_latest_by": "data_date"},
        ),
    ]
