# Generated by Django 4.1.5 on 2023-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0002_profile_torphies2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="trophies",
            new_name="trophies_edit",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="torphies2",
            new_name="trophies_view",
        ),
    ]
