# Generated by Django 4.1.5 on 2023-03-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0003_rename_trophies_profile_trophies_edit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZwiftRouteList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=200)),
                ("world_name", models.CharField(max_length=200)),
            ],
        ),
    ]
