# Generated by Django 4.1.5 on 2023-02-03 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0003_doc_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doc",
            old_name="title",
            new_name="data_type",
        ),
    ]
