# Generated by Django 4.1.5 on 2023-03-01 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garage", "0004_remove_profile_test_profile_bio_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="UserProfile",
        ),
    ]
