# Generated by Django 4.1.5 on 2023-02-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0005_kudos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kudos",
            options={"verbose_name_plural": "Kudos"},
        ),
        migrations.AddField(
            model_name="kudos",
            name="hex",
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kudos",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
