# Generated by Django 4.1.5 on 2023-03-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0006_doc_fit_data_doc_gpx_data_alter_doc_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="profile",
            name="strava_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
