# Generated by Django 4.1.5 on 2023-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0006_rename_userprofile_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trophies_raw",
            field=models.TextField(blank=True),
        ),
    ]
