# Generated by Django 4.1.5 on 2023-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0006_alter_kudos_options_kudos_hex_alter_kudos_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="kudosed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="kudos",
            name="hex",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
