# Generated by Django 4.1.5 on 2023-03-03 22:29

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0007_profile_trophies_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="trophies_raw",
        ),
        migrations.AddField(
            model_name="profile",
            name="trophies",
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
