# Generated by Django 4.1.5 on 2023-02-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0007_doc_kudosed_alter_kudos_hex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kudos",
            name="key",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
