# Generated by Django 4.1.5 on 2023-02-26 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0008_alter_kudos_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doc",
            old_name="doc_date",
            new_name="doc_date",
        ),
        migrations.RenameField(
            model_name="doc",
            old_name="doc_type",
            new_name="doc_type",
        ),
    ]
