# Generated by Django 4.1.5 on 2023-03-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0008_remove_profile_trophies_raw_profile_trophies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="trophies",
        ),
        migrations.AddField(
            model_name="profile",
            name="trophies_raw",
            field=models.TextField(blank=True),
        ),
    ]
