# Generated by Django 4.1.5 on 2023-03-03 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_remove_profile_trophies_profile_trophies_raw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="trophies_raw",
            new_name="trophies",
        ),
    ]
