# Generated by Django 4.1.5 on 2023-02-26 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0009_rename_doc_date_doc_doc_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doc",
            options={"get_latest_by": "doc_date"},
        ),
    ]
