# Generated by Django 4.1.5 on 2023-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0011_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="detail",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
