# Generated by Django 4.1.5 on 2023-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0012_doc_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="units_display_preference",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
