# Generated by Django 4.1.5 on 2023-03-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0012_alter_profile_trophies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="trophies",
            field=models.TextField(blank=True, null=True),
        ),
    ]
