# Generated by Django 4.1.5 on 2023-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garage", "0013_profile_units_display_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="habits",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
